### ISSUE TITLE
CPU implementation of the code.

### ISSUE THREAD

**Issue by aboudjelal** [adler-j/learned_gradient_tomography#3]
Bonjour,

Is there any cpu implementation of the code ?
I read in your paper that you have used the ’astra gpu’ backend. 

Regards

**Comment by adler-j** [comment]
The code should be runnable with a non-GPU version of Tensorflow and by selecting `impl='astra_cpu'` here https://github.com/adler-j/learned_gradient_tomography/blob/f358cc4e3611c480615d453b574253d511f73fe7/code/partially_learned_gradient_descent.py#L17 Beware that it is probably extremely slow though.

**Comment by aboudjelal** [comment]
Thank you for your answer,

when I execute the code : python3 partially_learned_gradient_descent_no_gradients.py .
I show this message, 

2019-03-18 14:48:17.850394: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594125000 Hz
2019-03-18 14:48:17.850835: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1ce2690 executing computations on platform Host. Devices:
2019-03-18 14:48:17.850875: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "partially_learned_gradient_descent_no_gradients.py", line 17, in <module>
    operator = odl.tomo.RayTransform(space, geometry)
  File "/home/abdel/.local/lib/python3.6/site-packages/odl/tomo/operators/ray_trafo.py", line 383, in __init__
    variant='forward', **kwargs)
  File "/home/abdel/.local/lib/python3.6/site-packages/odl/tomo/operators/ray_trafo.py", line 118, in __init__
    raise RuntimeError('no ray transform back-end available; '
RuntimeError: no ray transform back-end available; this requires 3rd party packages, please check the install docs

thanks

**Comment by adler-j** [comment]
Did you install ASTRA?

https://odlgroup.github.io/odl/getting_started/installing_extensions.html#astra-for-x-ray-tomography

**Comment by aboudjelal** [comment]
no I didn't 
i will try

**Comment by aboudjelal** [comment]
I installed ASTRA but some error

**Comment by adler-j** [comment]
Could you elaborate a bit more on what error?
